# Generated by Django 5.1.15 on 2026-08-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_push_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('OWNER', 'Owner'), ('ADMIN', 'Admin')], default='STAFF', max_length=10),
        ),
    ]
