# Generated by Django 5.1.15 on 2026-07-18 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('closing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('STOCK_CONFIRMED', 'Day-start stock confirmed'), ('IN_PROGRESS', 'In progress'), ('CLOSED', 'Closed')], default='NOT_STARTED', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stock_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('carry_forward_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('daily_closing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_day', to='closing.dailyclosing')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_days', to='catalog.outlet')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('outlet', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PeriodicStockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('counted_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_in_since_last_check', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('consumed_since_last_check', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodic_checks', to='catalog.ingredient')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_checks', to='catalog.outlet')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PreparationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('FRESH', 'Fresh'), ('CARRIED_FORWARD', 'Carried forward')], default='FRESH', max_length=16)),
                ('leftover_available_pieces', models.IntegerField(blank=True, null=True)),
                ('prep_unit', models.CharField(choices=[('PACK', 'Pack'), ('PIECE', 'Piece')], default='PIECE', max_length=5)),
                ('packs_used', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pieces_prepared', models.PositiveIntegerField(default=0)),
                ('wastage_pieces', models.IntegerField(blank=True, null=True)),
                ('carried_forward_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carry_forwards', to='closing.dailyclosingstockcount')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_logs', to='catalog.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('slip_image', models.ImageField(blank=True, null=True, upload_to='slips/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='catalog.outlet')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stock_ins', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_stock_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-stock_in_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_extracted_text', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('SLIP_EXTRACTED', 'Slip extracted'), ('MANUAL', 'Manual')], default='MANUAL', max_length=15)),
                ('unit_captured', models.CharField(choices=[('PACK', 'Pack'), ('PIECE', 'Piece')], default='PACK', max_length=5)),
                ('extracted_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('confirmed_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
                ('pack_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.packdefinition')),
                ('stock_in_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stockinrecord')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces_available', models.IntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_stock', to='catalog.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_stock', to='catalog.product')),
            ],
            options={
                'unique_together': {('outlet', 'product')},
            },
        ),
        migrations.CreateModel(
            name='DayStartStockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_carried_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('confirmed_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('discrepancy_reason', models.CharField(blank=True, choices=[('SPOILED', 'Spoiled'), ('MISCOUNTED_YESTERDAY', 'Miscounted yesterday'), ('SURPLUS_FOUND', 'Surplus found'), ('OTHER', 'Other')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient')),
                ('operating_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_checks', to='stock.operatingday')),
            ],
            options={
                'unique_together': {('operating_day', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='RawStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_stock', to='catalog.ingredient')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_stock', to='catalog.outlet')),
            ],
            options={
                'unique_together': {('outlet', 'ingredient')},
            },
        ),
    ]
