# Generated by Django 5.1.15 on 2026-07-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaystock',
            options={'ordering': ['product__name']},
        ),
        migrations.AlterModelOptions(
            name='rawstock',
            options={'ordering': ['ingredient__name']},
        ),
    ]
