# Generated by Django 5.1.15 on 2026-07-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_add_tax_fields_to_stockinitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinrecord',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
