# Generated by Django 5.1.15 on 2026-08-31 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_ingredient_group'),
        ('stock', '0008_stockinrecord_paid_from_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FryerOilChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.PositiveSmallIntegerField(choices=[(1, 'Pan 1'), (2, 'Pan 2')])),
                ('changed_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fryer_oil_changes', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fryer_oil_changes', to='catalog.outlet')),
            ],
            options={
                'ordering': ['-changed_at', '-created_at'],
            },
        ),
    ]
