# Generated by Django 5.1.15 on 2026-09-12 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_ingredient_group'),
        ('finance', '0005_account_role_access'),
        ('stock', '0009_fryer_oil_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockinrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APPROVED'), models.Q(('invoice_number', ''), _negated=True)), fields=('outlet', 'invoice_number', 'stock_in_date'), name='uniq_approved_invoice_per_outlet_per_date'),
        ),
    ]
