# Generated by Django 5.1.15 on 2026-09-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_stockinrecord_uniq_approved_invoice_per_outlet_per_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
