# Generated by Django 5.1.15 on 2026-07-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('base_unit', models.CharField(default='piece', max_length=30)),
                ('tracking_mode', models.CharField(choices=[('RECIPE_LINKED', 'Recipe-linked'), ('PERIODIC_COUNT', 'Periodic count')], default='RECIPE_LINKED', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('product_type', models.CharField(choices=[('SINGLE', 'Single'), ('COMBO', 'Combo')], default='SINGLE', max_length=10)),
                ('requires_preparation', models.BooleanField(default=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces_per_pack', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cost_per_pack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_definitions', to='catalog.ingredient')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.ingredient')),
            ],
            options={
                'ordering': ['alias_text'],
            },
        ),
        migrations.CreateModel(
            name='ComboComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_combo', models.PositiveIntegerField(default=1)),
                ('combo_product', models.ForeignKey(limit_choices_to={'product_type': 'COMBO'}, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.product')),
                ('component_product', models.ForeignKey(limit_choices_to={'product_type': 'SINGLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='in_combos', to='catalog.product')),
            ],
            options={
                'unique_together': {('combo_product', 'component_product')},
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='catalog.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('product', 'ingredient')},
            },
        ),
    ]
