# Generated by Django 5.1.15 on 2026-07-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_recipe_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='tracking_mode',
            field=models.CharField(choices=[('RECIPE_LINKED', 'Recipe-linked'), ('PERIODIC_COUNT', 'Periodic count'), ('ONE_TIME', 'One-time purchase')], default='RECIPE_LINKED', max_length=15),
        ),
    ]
