# Generated by Django 5.1.15 on 2026-08-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_ingredient_tracking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='group',
            field=models.CharField(choices=[('BEVERAGE', 'Beverages'), ('CHICKEN_PIECE', 'Chicken (Main)'), ('SNACK', 'Snacks & Balls'), ('BURGER_WRAP', 'Burgers & Wraps'), ('SUPPLY', 'Supplies'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
