# Generated by Django 5.1.15 on 2026-09-23 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_onboarding_completed(apps, schema_editor):
    """Every Organization that already existed before this feature shipped is,
    by definition, already operational — stamp it as onboarded so its owner
    isn't force-routed into the new first-login wizard on next login."""
    Organization = apps.get_model("catalog", "Organization")
    Organization.objects.filter(onboarding_completed_at__isnull=True).update(
        onboarding_completed_at=models.F("created_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_ingredient_bundle_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TenantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=120)),
                ('owner_name', models.CharField(max_length=120)),
                ('owner_phone', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_applications', to='catalog.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_applications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RunPython(backfill_onboarding_completed, migrations.RunPython.noop),
    ]
