# Generated by Django 5.1.15 on 2026-09-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_globalize_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantapplication',
            name='org_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
