# Generated by Django 5.1.15 on 2026-09-30 19:01

from django.db import migrations, models


def mark_template_organization(apps, schema_editor):
    """Whichever existing organization has the most SalesChannel rows is the
    real, in-use setup (CP Five Star at time of writing) — mark it as the
    template new organizations get seeded from. No-op on an empty DB."""
    Organization = apps.get_model("catalog", "Organization")
    SalesChannel = apps.get_model("sales", "SalesChannel")

    best = (
        SalesChannel.objects.values("organization_id")
        .annotate(n=models.Count("id"))
        .order_by("-n")
        .first()
    )
    if best and best["n"] > 0:
        Organization.objects.filter(pk=best["organization_id"]).update(is_channel_template=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_tenantapplication_org_address'),
        ('sales', '0007_require_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_channel_template',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_template_organization, migrations.RunPython.noop),
    ]
