# Generated by Django 5.1.15 on 2026-07-18 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('PARTIAL', 'Partial'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.saleschannel')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='catalog.outlet')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked')], default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('has_variance_flag', models.BooleanField(default=False)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closings', to='catalog.outlet')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-closing_date'],
                'unique_together': {('outlet', 'closing_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyChannelDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.saleschannel')),
                ('daily_closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_discounts', to='closing.dailyclosing')),
            ],
            options={
                'unique_together': {('daily_closing', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='DailyClosingSalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source', models.CharField(choices=[('STAFF_ENTRY', 'Staff entry'), ('SYSTEM_DERIVED', 'System derived')], default='STAFF_ENTRY', max_length=15)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.saleschannel')),
                ('daily_closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_lines', to='closing.dailyclosing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'unique_together': {('daily_closing', 'product', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='DailyClosingStockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_pieces', models.IntegerField(default=0)),
                ('wastage_pieces', models.IntegerField(default=0)),
                ('remains_pieces', models.IntegerField(default=0)),
                ('app_channel_sold', models.IntegerField(default=0)),
                ('flag', models.BooleanField(default=False)),
                ('daily_closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='closing.dailyclosing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'unique_together': {('daily_closing', 'product')},
            },
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BKASH', 'bKash'), ('CARD', 'Card')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='closing.dailyclosing')),
            ],
            options={
                'unique_together': {('daily_closing', 'method')},
            },
        ),
    ]
