# Generated by Django 5.1.15 on 2026-08-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financialaccount_is_primary_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccount',
            name='is_primary_cash',
            field=models.BooleanField(default=False, help_text="Marks this as the shop's main cash account. Day-closing cash is computed as total offline sales minus all other payment entries."),
        ),
    ]
