# Generated by Django 5.1.15 on 2026-09-03 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_financialaccount_is_primary_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STAFF', 'Staff'), ('OWNER', 'Owner'), ('ADMIN', 'Admin')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_access', to='finance.financialaccount')),
            ],
            options={
                'ordering': ['role', 'account__name'],
                'unique_together': {('role', 'account')},
            },
        ),
    ]
