# Generated by Django 5.1.15 on 2026-09-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_organization_ingredient_organization_and_more'),
        ('finance', '0005_account_role_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_accounts', to='catalog.organization'),
        ),
    ]
