# Generated by Django 5.1.15 on 2026-07-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('settlement_type', models.CharField(choices=[('DIRECT_TO_ACCOUNT', 'Direct to account'), ('COLLECTED_AT_OUTLET', 'Collected at outlet')], default='COLLECTED_AT_OUTLET', max_length=20)),
                ('integration_type', models.CharField(choices=[('API_SYNC', 'API sync'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10)),
                ('commission_basis', models.CharField(choices=[('DISCOUNTED_PRICE', 'Discounted price'), ('ORIGINAL_PRICE', 'Original price')], default='DISCOUNTED_PRICE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderLevelOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed amount')], max_length=12)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_offers', to='sales.saleschannel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed amount')], max_length=12)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalog.product')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='sales.saleschannel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_prices', to='catalog.product')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sales.saleschannel')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ChannelIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='sales.saleschannel')),
            ],
        ),
    ]
