# Generated by Django 5.1.15 on 2026-07-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelpromotion',
            options={'ordering': ['-effective_from', 'id']},
        ),
        migrations.AlterModelOptions(
            name='orderleveloffer',
            options={'ordering': ['-effective_from', 'id']},
        ),
    ]
