# Generated by Django 5.1.15 on 2026-08-12 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_ingredient_group'),
        ('sales', '0002_alter_channelpromotion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMenuMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_name', models.CharField(db_index=True, max_length=255)),
                ('quantity_multiplier', models.PositiveIntegerField(default=1, help_text='Multiply the order qty by this to get internal product pieces.')),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_maps', to='sales.saleschannel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_maps', to='catalog.product')),
            ],
            options={
                'ordering': ['external_name'],
                'unique_together': {('channel', 'external_name')},
            },
        ),
    ]
