# Generated by Django 5.1.15 on 2026-08-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_channel_menu_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelPrice',
        ),
    ]
