# Generated by Django 5.1.15 on 2026-09-07 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_require_organization'),
        ('sales', '0007_require_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpromotion',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_promotions', to='catalog.organization'),
        ),
        migrations.AddField(
            model_name='orderleveloffer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_level_offers', to='catalog.organization'),
        ),
    ]
