# Generated by Django 5.1.15 on 2026-07-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_seed_electricity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BKASH', 'bKash')], default='CASH', max_length=10),
        ),
    ]
