# Generated by Django 5.1.15 on 2026-09-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_organization_ingredient_organization_and_more'),
        ('costs', '0005_add_paid_from_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_categories', to='catalog.organization'),
        ),
    ]
