# Generated by Django 5.1.15 on 2026-10-05 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_globalize_otherincomecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otherincome',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_other_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
